apiVersion: v1
kind: Namespace
metadata:
  name: payment-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: mash02/payment-service:latest
          ports:
            - containerPort: 50056
          envFrom:
            - secretRef:
                name: payment-service-secret
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 50056
      targetPort: 50056
  type: ClusterIP
