name: Deploy Payment Service to K3s

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: mash02/payment-service
  IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create namespace.yaml
        run: |
          cat <<EOF > namespace.yaml
          apiVersion: v1
          kind: Namespace
          metadata:
            name: payment-service
          EOF

      - name: Write payment-service-secret.yaml from GitHub Secret
        run: |
          echo "${{ secrets.PAYMENT_SERVICE_SECRET_YAML_BASE64 }}" | base64 -d > payment-service-secret.yaml

      - name: Create payment-service.yaml (Deployment + Service)
        shell: bash
        run: |
          cat <<EOF > payment-service.yaml
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: payment-service
            namespace: payment-service
            labels:
              app: payment-service
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: payment-service
            template:
              metadata:
                labels:
                  app: payment-service
              spec:
                containers:
                  - name: payment-service
                    image: ${IMAGE_NAME}:${IMAGE_TAG}
                    ports:
                      - containerPort: 50056
                    envFrom:
                      - secretRef:
                          name: payment-service-secret
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: payment-service
            namespace: payment-service
          spec:
            selector:
              app: payment-service
            ports:
              - protocol: TCP
                port: 50056
                targetPort: 50056
            type: ClusterIP
          EOF

      - name: Check generated files
        run: |
          ls -la
          echo "--- namespace.yaml ---" && cat namespace.yaml
          echo "--- payment-service-secret.yaml ---" && cat payment-service-secret.yaml
          echo "--- payment-service.yaml ---" && cat payment-service.yaml

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Install OpenSSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'echo "SSH connection successful"'

      - name: Deploy to EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} "mkdir -p ~/deploy/payment-service"
          scp namespace.yaml payment-service-secret.yaml payment-service.yaml ubuntu@${{ secrets.EC2_HOST }}:~/deploy/payment-service/
          ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/deploy/payment-service
            sudo kubectl apply -f namespace.yaml
            sudo kubectl apply -f payment-service-secret.yaml
            sudo kubectl apply -f payment-service.yaml
          EOF
